
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int NOT_EQUAL = 23;
  public static final int MUL_EQUAL = 14;
  public static final int GREATER = 22;
  public static final int DECR = 3;
  public static final int INCR = 2;
  public static final int I_INT = 45;
  public static final int LESS = 20;
  public static final int I_SHORT = 48;
  public static final int I_FOR = 43;
  public static final int SEMICOLON = 54;
  public static final int I_VOID = 50;
  public static final int I_DEFAULT = 40;
  public static final int I_CONST = 38;
  public static final int COMMA = 55;
  public static final int I_ELSE = 42;
  public static final int DIV = 8;
  public static final int FLOAT_NUMBER = 28;
  public static final int I_IF = 44;
  public static final int LESS_EQUAL = 21;
  public static final int I_READ = 52;
  public static final int DIV_EQUAL = 15;
  public static final int I_RETURN = 47;
  public static final int I_WRITE = 53;
  public static final int FLOAT_POINT_NUMBER = 29;
  public static final int EOF = 0;
  public static final int OPEN_KEY = 16;
  public static final int CLOSE_KEY = 17;
  public static final int EQUAL = 4;
  public static final int LOGICAL_OR = 24;
  public static final int GREATER_EQUAL = 19;
  public static final int I_LONG = 46;
  public static final int error = 1;
  public static final int MUL = 7;
  public static final int LITERAL_CHAR = 30;
  public static final int ADD = 5;
  public static final int I_SWITCH = 49;
  public static final int NUMBER = 32;
  public static final int LITERAL_STR = 27;
  public static final int MOD = 9;
  public static final int CLOSE_BRACKET = 11;
  public static final int OPEN_BRACKET = 10;
  public static final int HEXADECIMAL_NUMBER = 33;
  public static final int EQUAL_TO = 18;
  public static final int COLON = 57;
  public static final int SUB_EQUAL = 13;
  public static final int ADD_EQUAL = 12;
  public static final int OCTAL_NUMBER = 31;
  public static final int I_CHAR = 37;
  public static final int LOGICAL_NOT = 26;
  public static final int LOGICAL_AND = 25;
  public static final int I_CONTINUE = 39;
  public static final int I_BREAK = 35;
  public static final int I_CASE = 36;
  public static final int BINARY_NUMBER = 34;
  public static final int I_DO = 41;
  public static final int SUB = 6;
  public static final int I_WHILE = 51;
  public static final int IDENTIFIER = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INCR",
  "DECR",
  "EQUAL",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "MOD",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "ADD_EQUAL",
  "SUB_EQUAL",
  "MUL_EQUAL",
  "DIV_EQUAL",
  "OPEN_KEY",
  "CLOSE_KEY",
  "EQUAL_TO",
  "GREATER_EQUAL",
  "LESS",
  "LESS_EQUAL",
  "GREATER",
  "NOT_EQUAL",
  "LOGICAL_OR",
  "LOGICAL_AND",
  "LOGICAL_NOT",
  "LITERAL_STR",
  "FLOAT_NUMBER",
  "FLOAT_POINT_NUMBER",
  "LITERAL_CHAR",
  "OCTAL_NUMBER",
  "NUMBER",
  "HEXADECIMAL_NUMBER",
  "BINARY_NUMBER",
  "I_BREAK",
  "I_CASE",
  "I_CHAR",
  "I_CONST",
  "I_CONTINUE",
  "I_DEFAULT",
  "I_DO",
  "I_ELSE",
  "I_FOR",
  "I_IF",
  "I_INT",
  "I_LONG",
  "I_RETURN",
  "I_SHORT",
  "I_SWITCH",
  "I_VOID",
  "I_WHILE",
  "I_READ",
  "I_WRITE",
  "SEMICOLON",
  "COMMA",
  "IDENTIFIER",
  "COLON"
  };
}

