
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int i_case = 33;
  public static final int i_for = 40;
  public static final int mul = 7;
  public static final int add = 5;
  public static final int mod = 9;
  public static final int octal_number = 27;
  public static final int less_equal = 19;
  public static final int i_short = 45;
  public static final int i_const = 35;
  public static final int not_equal = 21;
  public static final int identifier = 49;
  public static final int i_do = 38;
  public static final int mul_equal = 14;
  public static final int equal_to = 16;
  public static final int i_return = 44;
  public static final int hexadecimal_number = 29;
  public static final int equal = 4;
  public static final int i_default = 37;
  public static final int i_void = 47;
  public static final int i_continue = 36;
  public static final int sub = 6;
  public static final int EOF = 0;
  public static final int logical_or = 22;
  public static final int i_switch = 46;
  public static final int error = 1;
  public static final int i_else = 39;
  public static final int div_equal = 15;
  public static final int open_bracket = 10;
  public static final int ERROR = 31;
  public static final int i_long = 43;
  public static final int greater = 20;
  public static final int literal_str = 25;
  public static final int i_if = 41;
  public static final int float_number = 26;
  public static final int float_point_number = 30;
  public static final int i_break = 32;
  public static final int sub_equal = 13;
  public static final int add_equal = 12;
  public static final int decr = 3;
  public static final int incr = 2;
  public static final int logical_and = 23;
  public static final int logical_not = 24;
  public static final int less = 18;
  public static final int div = 8;
  public static final int greater_equal = 17;
  public static final int i_char = 34;
  public static final int i_while = 48;
  public static final int i_int = 42;
  public static final int number = 28;
  public static final int close_bracket = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "incr",
  "decr",
  "equal",
  "add",
  "sub",
  "mul",
  "div",
  "mod",
  "open_bracket",
  "close_bracket",
  "add_equal",
  "sub_equal",
  "mul_equal",
  "div_equal",
  "equal_to",
  "greater_equal",
  "less",
  "less_equal",
  "greater",
  "not_equal",
  "logical_or",
  "logical_and",
  "logical_not",
  "literal_str",
  "float_number",
  "octal_number",
  "number",
  "hexadecimal_number",
  "float_point_number",
  "ERROR",
  "i_break",
  "i_case",
  "i_char",
  "i_const",
  "i_continue",
  "i_default",
  "i_do",
  "i_else",
  "i_for",
  "i_if",
  "i_int",
  "i_long",
  "i_return",
  "i_short",
  "i_switch",
  "i_void",
  "i_while",
  "identifier"
  };
}

